backend/setup/urls.py
# myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

urlpatterns = [
    path("api/", include("api.urls_api")),  # URLs da sua API
    re_path(r"^.*$", TemplateView.as_view(template_name="index.html")),  # Rota do React
]

backend/api/models/ClienteModel.py
from .CustomModel import CustomModel
from django.db import models
from .EmpresaModel import EmpresaModel
from .EnderecoModel import EnderecoModel
from django.utils import timezone
import uuid
from api.utils import Utils


class ClienteModel(CustomModel):
    id_cliente = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    nome = models.CharField(max_length=255)
    telefone = models.CharField(max_length=20, null=True)
    ultima_compra = models.DateField(null=True, blank=True)
    tipo_cliente = models.CharField(max_length=50, null=True, blank=True)
    descricao = models.CharField(max_length=300, null=True, blank=True)
    endereco = models.ForeignKey(EnderecoModel, on_delete=models.SET_NULL, null=True)
    empresa = models.ForeignKey(EmpresaModel, on_delete=models.CASCADE, null=True)
    class Meta:
        db_table = 'cliente'

backend/api/models/ConfiguracaoModel.py
import uuid
from .CustomModel import CustomModel
from django.db import models
from .UsuarioModel import UsuarioModel
from django.utils import timezone
from api.utils import Utils

class ConfiguracaoModel(CustomModel):
    id_configuracao = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    usuario = models.ForeignKey(UsuarioModel, on_delete=models.CASCADE, null=True)
    codigo = models.IntegerField(null=True)
    titulo = models.TextField(blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)
    descricao_interna = models.TextField(blank=True, null=True)
    status_acesso = models.BooleanField(default=True)
    class Meta:
        db_table = 'configuracao'

backend/api/models/EnderecoModel.py
from .CustomModel import CustomModel
from django.db import models
import uuid

class EnderecoModel(CustomModel):
    id_endereco = models.AutoField(primary_key=True)
    id = models.UUIDField(default=uuid.uuid4, editable=False)
    rua = models.CharField(max_length=255,)
    numero = models.CharField(max_length=10, null=True, blank=True)
    bairro = models.CharField(max_length=100, null=True)
    cidade = models.CharField(max_length=100, null=True)
    estado = models.CharField(max_length=50, null=True)
    codigo_postal = models.CharField(max_length=30, null=True)
    descricao = models.TextField(null=True, max_length=500)
    class Meta:
        db_table = 'endereco'

backend/api/models/LojaModel.py
from django.db import models
from .CustomModel import CustomModel
import uuid
from .EmpresaModel import EmpresaModel
from .EnderecoModel import EnderecoModel 
from .UsuarioModel import UsuarioModel


class LojaModel(CustomModel):
    id_loja = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nome = models.CharField(max_length=255)
    numero_telefone = models.CharField(max_length=50, null=True)
    horario_operacao_inicio = models.TimeField(null=True, blank=True)
    horario_operacao_fim = models.TimeField(null=True, blank=True)
    segunda = models.BooleanField(default=False)
    terca = models.BooleanField(default=False)
    quarta = models.BooleanField(default=False)
    quinta = models.BooleanField(default=False)
    sexta = models.BooleanField(default=False)
    sabado = models.BooleanField(default=False)
    domingo = models.BooleanField(default=False)
    empresa = models.ForeignKey('EmpresaModel', on_delete=models.CASCADE)
    endereco = models.ForeignKey('EnderecoModel', on_delete=models.SET_NULL, null=True)
    class Meta:
        db_table = 'loja'

class AssociadoModel(CustomModel):
    id_associado = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    status_acesso = models.BooleanField(null=True)
    usuario = models.ForeignKey('UsuarioModel', on_delete=models.CASCADE, null=True)
    loja = models.ForeignKey('LojaModel', on_delete=models.CASCADE, null=True)
    class Meta:
        db_table = 'loja_associado'

backend/api/views/ClienteView.py
from api.utils import Utils
from api.user import UserInfo
from api.permissions import CustomPermission
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action        
from api.services import ClienteService, EnderecoService
import json
 
 
class ClienteView(viewsets.ViewSet):
    permission_classes = [CustomPermission]  # Permissão base

    def get_permissions(self):
        """
        Ajusta as permissões dinamicamente com base na view.
        """

        permissions = [permission() for permission in self.permission_classes]
        for permission in permissions:
            if isinstance(permission, CustomPermission):
                # Ajuste os parâmetros conforme necessário
                permission.codigo_model = "cliente"
                permission.auth_required = True
        return permissions

    
    def create(self, request):
        try:
            data = json.loads(request.body)
            empresa_id = UserInfo.get_id_empresa(request)

            cliente_data = data.get("cliente", {})
            cliente_data["empresa"] = empresa_id
            
            # Criar o cliente
            cliente, status_cliente, msg_cliente = ClienteService.create_cliente(cliente_data)
            
            if status_cliente:
                response_data = Utils.modelo_para_json(cliente)
                return Response({
                    "success": status_cliente,
                    "data": response_data,
                    "message": msg_cliente
                })
            else:
                return Response({
                    "success": False,
                    "message": msg_cliente
                }, status=status.HTTP_400_BAD_REQUEST)
        except json.JSONDecodeError:
            return Response({
                "error": "Erro ao processar dados JSON."
            }, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({
                "error": str(e)
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=True, methods=['put'], url_path='atualizar')
    def put(self, request, pk=None):
        """Handle PUT requests to update a cliente by ID."""
        try:
            cliente_data = request.data.get("cliente", {})

            if not cliente_data.get("id_cliente"):
                return Response({"success": False, "message": "ID do cliente não fornecido para atualização."}, status=status.HTTP_400_BAD_REQUEST)

            cliente, status_cliente, msg_cliente = ClienteService.update_cliente(cliente_data["id_cliente"], cliente_data)

            if status_cliente:
                return Response({ "data": Utils.modelo_para_json(cliente), "message": msg_cliente}, status=status.HTTP_200_OK)
            else:
                return Response({"success": False, "message": msg_cliente}, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=True, methods=['get'], url_path='detalhes')
    def get(self, request, pk=None):
        """Handle GET requests to retrieve a cliente by ID."""
        try:
            data = ClienteService.get_cliente(pk)
            if data.get('success'):
                return Response(data, status=status.HTTP_200_OK)
            return Response(data, status=data.get('status', status.HTTP_400_BAD_REQUEST))
        except Exception as e:
            return Response({"message": f"Ocorreu um erro ao processar a solicitação: {e}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=True, methods=['delete'], url_path='excluir')
    def delete_cliente(self, request, pk=None):
        """Handle DELETE requests to delete a cliente by ID."""
        empresa_id = UserInfo.get_id_empresa(request)
        
        # Chama o serviço para excluir o cliente e obtém a resposta
        success, message = ClienteService.delete_cliente(pk, empresa_id)
        
        # Define o status HTTP baseado no sucesso da operação
        if success:
            return Response({ "message": message}, status=status.HTTP_200_OK)
        else:
            return Response({"success": False, "message": message}, status=status.HTTP_400_BAD_REQUEST)

    @action(detail=False, methods=['get'], url_path='clientes-empresa')
    def get_clientes_by_empresa(self, request):
        try:
            empresa_id = UserInfo.get_id_empresa(request)
            clientes_data = ClienteService.get_clientes_by_empresa(empresa_id)
            
            # Verifica se há dados retornados e determina o status
            if clientes_data:
                return Response({ "data": clientes_data}, status=status.HTTP_200_OK)
            else:
                return Response({"message": "Não foram encontrados clientes para esta empresa."}, status=status.HTTP_404_NOT_FOUND)

        except Exception as e:
            return Response({"error": "Erro interno do servidor."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=False, methods=['get'], url_path='clientes')
    def get_cliente(self, request):
        empresa_id = UserInfo.get_id_empresa(request)
        response_data, status_code = ClienteService.get_cliente(empresa_id)
        return Response(response_data, status=status_code)

    @action(detail=True, methods=['get'], url_path='vendas')
    def get_vendas_by_cliente(self, request, pk=None):
        response_data, status_code = ClienteService.get_vendas_by_cliente(pk)
        return Response(response_data, status=status_code)

backend/api/views/ConfiguracaoView.py
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action
from api.services import ConfiguracaoService
from api.models import ConfiguracaoModel
from api.serializers import ConfiguracaoSerializer
from api.user import UserInfo
from api.permissions import CustomPermission

class ConfiguracaoView(viewsets.ViewSet):
    permission_classes = CustomPermission(codigo_model="configuracao", auth_required=True)

    @action(detail=False, methods=['get'], url_path='usuario/(?P<id_usuario>\d+)/')
    def get_configuracoes_usuario(self, request, id_usuario=None):
        response_data, status_code = ConfiguracaoService.get_configuracoes_usuario(id_usuario)
        return Response(response_data, status=status_code)

    @action(detail=False, methods=['post'], url_path='session/(?P<id_usuario>\d+)/')
    def configuracao_set_session(self, request, id_usuario=None):
        response_data, status_code = ConfiguracaoService.configuracao_set_session(request, id_usuario)
        return Response(response_data, status=status_code)

    @action(detail=False, methods=['post'], url_path='criar-padrao/')
    def criar_configuracoes_padrao(self, request):
        listModel = request.data.get('listModel', [])
        response_data, status_code = ConfiguracaoService.criar_configuracoes_padrao(listModel)
        return Response(response_data, status=status_code)

    @action(detail=False, methods=['get'], url_path='listar-padrao/')
    def list_configuracoes_padrao(self, request):
        usuario = UserInfo.get_id_usuario(request)
        response_data = ConfiguracaoService.list_configuracoes_padrao(usuario)
        return Response({"data": response_data, "success": True}, status=status.HTTP_200_OK)

backend/api/views/EmpresaView.py
# views.py
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action
from api.models import EmpresaModel
from api.serializers import EmpresaSerializer
from api.services import  EmpresaService
from api.permissions import CustomPermission

class EmpresaView(viewsets.ViewSet):
    permission_classes = [CustomPermission(codigo_model="empresa", auth_required=True)]

    def list_private(self, request):
        try:
            empresas = EmpresaService.get_all_empresas()
            serializer = EmpresaSerializer(empresas, many=True)
            return Response({"data": serializer.data, "success": True}, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def create(self, request):
        serializer = EmpresaSerializer(data=request.data)
        if serializer.is_valid():
            try:
                empresa = EmpresaService.create_empresa(serializer.validated_data)
                return Response({"data": EmpresaSerializer(empresa).data, "success": True}, status=status.HTTP_201_CREATED)
            except Exception as e:
                return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)
        return Response({"error": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)

    def retrieve(self, request, pk=None):
        try:
            empresa = EmpresaService.get_empresa_by_id(pk)
            serializer = EmpresaSerializer(empresa)
            return Response({"data": serializer.data, "success": True}, status=status.HTTP_200_OK)
        except EmpresaModel.DoesNotExist:
            return Response({"error": "Empresa não encontrada"}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def update(self, request, pk=None):
        try:
            empresa = EmpresaService.get_empresa_by_id(pk)
            serializer = EmpresaSerializer(empresa, data=request.data, partial=True)
            if serializer.is_valid():
                updated_empresa = EmpresaService.update_empresa(pk, serializer.validated_data)
                return Response({"data": EmpresaSerializer(updated_empresa).data, "success": True}, status=status.HTTP_200_OK)
            return Response({"error": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
        except EmpresaModel.DoesNotExist:
            return Response({"error": "Empresa não encontrada"}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def destroy(self, request, pk=None):
        try:
            EmpresaService.delete_empresa(pk)
            return Response({"success": True}, status=status.HTTP_204_NO_CONTENT)
        except EmpresaModel.DoesNotExist:
            return Response({"error": "Empresa não encontrada"}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=False, methods=['get'], url_path='telefone/(?P<telefone>[\d\+\-\s]+)')
    def telefone_existe(self, request, telefone=None):
        existe = EmpresaService.telefone_existe(telefone)
        return Response({"existe": existe}, status=status.HTTP_200_OK)

    @action(detail=False, methods=['get'], url_path='cpf/(?P<cpf>\d{11})')
    def cpf_existe(self, request, cpf=None):
        existe = EmpresaService.cpf_existe(cpf)
        return Response({"existe": existe}, status=status.HTTP_200_OK)

    @action(detail=False, methods=['get'], url_path='cnpj/(?P<cnpj>\d{14})')
    def cnpj_existe(self, request, cnpj=None):
        existe = EmpresaService.cnpj_existe(cnpj)
        return Response({"existe": existe}, status=status.HTTP_200_OK)

backend/api/views/EnderecoView.py
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from api.permissions import CustomPermission
from api.services import  EnderecoService
from api.models import EnderecoModel
from api.utils import Utils

class EnderecoView(viewsets.ViewSet):
    permission_classes = [CustomPermission(codigo_model="endereco", auth_required=True)]

    @action(detail=False, methods=['post'])
    def create_endereco(self, request):
        data = request.data
        endereco, status_success, msg = EnderecoService.create_endereco_data(data)
        if status_success:
            response_data = Utils.modelo_para_json(endereco)
            return Response({"success": status_success, "data": response_data, "message": msg}, status=status.HTTP_201_CREATED)
        return Response({"success": status_success, "message": msg}, status=status.HTTP_400_BAD_REQUEST)

    @action(detail=True, methods=['put'])
    def update_endereco(self, request, pk=None):
        endereco_id = pk
        data = request.data
        endereco, status_success, msg = EnderecoService.update_endereco_data(endereco_id, data)
        if status_success:
            return Response({"success": status_success, "data": Utils.modelo_para_json(endereco), "message": msg}, status=status.HTTP_200_OK)
        return Response({"success": status_success, "message": msg}, status=status.HTTP_404_NOT_FOUND)

backend/api/views/ErroView.py
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse


from api.permissions import CustomPermission
from rest_framework import viewsets, status

class ErroView(viewsets.ViewSet):
    permission_classes = [CustomPermission(codigo_model="configuracao", auth_required=True)]

    @staticmethod
    def erro(request, error_message):
        return JsonResponse({"error_message": error_message}, status=500)

backend/api/templates/loja/modal_loja.html
{% block content %}
  
  
<!-- Modal -->
<div class="modal fade" id="ModalLoja" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog  modal-md modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title fw-bold font-monospace" id="lojaModalLabel" >
            {% if text_loja %} Detalhes da Loja{% endif%}
            {% if form_loja %} Formulario da Loja{% endif%}
        </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body  fonrt-monospace"  style="font-size: 0.8rem;">
            {% if text_loja %} 
            <div class="form-group">
                <label for="nome" class="fw-bold">Nome da Loja:</label>
                <span id="nome">{{ text_loja.nome }}</span>
              </div>
              <div class="form-group">
                <label  class="fw-bold" for="numero_telefone">Número Telefone:</label>
                <span id="numero_telefone">{{ text_loja.numero_telefone }}</span>
              </div>
              <div class="alert alert-warning font-monospace" role="alert">
                <i class="bi bi-exclamation-triangle-fill"></i>
                <strong>Atenção:</strong> As configurações  de horarios permitem fazer uma gestão completa, configure com atenção.
            </div>
              <div class="form-group">
                <label  class="fw-bold" for="horario_operacao">Horario de Operacao:</label>
                <ul class="list-unstyled">
                    <li><i class="bi bi-calendar-day"></i> Segunda-feira: {% if text_loja.segunda %}Aberto das {{ text_loja.horario_operacao_inicio|time:"H:i" }} às {{ text_loja.horario_operacao_fim|time:"H:i" }}{% else %}Fechado{% endif %}</li>
                    <li><i class="bi bi-calendar-day"></i> Terça-feira: {% if text_loja.terca %}Aberto das {{ text_loja.horario_operacao_inicio|time:"H:i" }} às {{ text_loja.horario_operacao_fim|time:"H:i" }}{% else %}Fechado{% endif %}</li>
                    <li><i class="bi bi-calendar-day"></i> Quarta-feira: {% if text_loja.quarta %}Aberto das {{ text_loja.horario_operacao_inicio|time:"H:i" }} às {{ text_loja.horario_operacao_fim|time:"H:i" }}{% else %}Fechado{% endif %}</li>
                    <li><i class="bi bi-calendar-day"></i> Quinta-feira: {% if text_loja.quinta %}Aberto das {{ text_loja.horario_operacao_inicio|time:"H:i" }} às {{ text_loja.horario_operacao_fim|time:"H:i" }}{% else %}Fechado{% endif %}</li>
                    <li><i class="bi bi-calendar-day"></i> Sexta-feira: {% if text_loja.sexta %}Aberto das {{ text_loja.horario_operacao_inicio|time:"H:i" }} às {{ text_loja.horario_operacao_fim|time:"H:i" }}{% else %}Fechado{% endif %}</li>
                    <li><i class="bi bi-calendar-day"></i> Sábado: {% if text_loja.sabado %}Aberto das {{ text_loja.horario_operacao_inicio|time:"H:i" }} às {{ text_loja.horario_operacao_fim|time:"H:i" }}{% else %}Fechado{% endif %}</li>
                    <li><i class="bi bi-calendar-day"></i> Domingo: {% if text_loja.domingo %}Aberto das {{ text_loja.horario_operacao_inicio|time:"H:i" }} às {{ text_loja.horario_operacao_fim|time:"H:i" }}{% else %}Fechado{% endif %}</li>
                </ul>
               </div>
       
               <p class="form-title font-monospace mb-1 mt-2 fw-bolder" >Endereço</p>
               <hr class="fw-border text-black mt-0 mb-2" >
              <div class="form-group">
                <label for="text_rua" class="fw-bold">Rua:</label>
                <span id="text_rua">{{ text_endereco.rua }}</span>
              </div>
              <div class="form-group">
                <label  class="fw-bold" for="text_numero">Número:</label>
                <span id="text_numero">{{ text_endereco.numero }}</span>
              </div>
              <div class="form-group">
                <label  class="fw-bold" for="text_codigo_postal">Código Postal:</label>
                <span id="text_codigo_postal">{{ text_endereco.codigo_postal }}</span>
              </div>

              <div class="form-group">
                <label  class="fw-bold" for="text_cidade">Bairro:</label>
                <span id="text_cidade">{{ text_endereco.bairro }}</span>
              </div>
              <div class="form-group">
                <label class="fw-bold"  for="text_cidade">Cidade:</label>
                <span id="text_cidade">{{ text_endereco.cidade }}</span>
              </div>
              <div class="form-group">
                <label  class="fw-bold" for="text_estado">Estado:</label>
                <span id="text_estado">{{ text_endereco.estado }}</span>
              </div>
              <div class="form-group">
                <label  class="fw-bold"  for="text_descricao">Descrição:</label>
                <span id="text_descricao">{{ text_endereco.descricao }}</span>
              </div>
             
              {% endif%}
            {% if form_loja %}   
            <form method="post" id="form_cadastro" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="form-floating mb-2 ">
                    {{ form_loja.nome }}
                    <label for="id_nome" style="font-size: 0.8rem;">nome para referenciar a loja:</label>
                </div>
                <div class="form-floating mb-2 ">
                    {{ form_loja.numero_telefone }}
                    <label for="id_numero_telefone" style="font-size: 0.8rem;">Telefone</label>
                </div>
<div class="form-group">
    <label>Selecione os dias de funcionamento::</label>
    <div class="row">
        <div class="col-6 col-md-4">
            <div class="form-check py-0 p-1 m-0">
                {{ form_loja.segunda }}
                <label class="form-check-label" for="id_segunda">Segunda-feira</label>
            </div>
        </div>
        <div class="col-6 col-md-4">
            <div class="form-check py-0 p-1 m-0">
                {{ form_loja.terca }}
                <label class="form-check-label" for="id_terca">Terça-feira</label>
            </div>
        </div>
        <div class="col-6 col-md-4">
            <div class="form-check py-0 p-1 m-0">
                {{ form_loja.quarta }}
                <label class="form-check-label" for="id_quarta">Quarta-feira</label>
            </div>
        </div>
        <div class="col-6 col-md-4">
            <div class="form-check py-0 p-1 m-0">
                {{ form_loja.quinta }}
                <label class="form-check-label" for="id_quinta">Quinta-feira</label>
            </div>
        </div>
        <div class="col-6 col-md-4">
            <div class="form-check py-0 p-1 m-0">
                {{ form_loja.sexta }}
                <label class="form-check-label" for="id_sexta">Sexta-feira</label>
            </div>
        </div>
        <div class="col-6 col-md-4">
            <div class="form-check py-0 p-1 m-0">
                {{ form_loja.sabado }}
                <label class="form-check-label" for="id_sabado">Sábado</label>
            </div>
        </div>
        <div class="col-6 col-md-4">
            <div class="form-check py-0 p-1 m-0">
                {{ form_loja.domingo }}
                <label class="form-check-label" for="id_domingo">Domingo</label>
            </div>
        </div>
    </div>
</div>
 
              <div class="form-group">
                <div class="row">
                    <div class="col p-1">
                        <div class="form-floating mb-2">
                    {{ form_loja.horario_operacao_inicio }}
                        <label for="horario_operacao_inicio" style="font-size: 0.8rem;">Horário de inicio:</label>
                    </div>
                    </div>
                    <div class="col p-1">
                        <div class="form-floating mb-2">
                           {{ form_loja.horario_operacao_fim   }}
                             <label for="horario_operacao_fim" style="font-size: 0.8rem;" >Horário de Fim:</label>
                        </div>
                    </div>
                </div>
              </div>
              <p class="form-title font-monospace mb-1 mt-2 fw-bolder" >Endereço</p>
              <hr class="fw-border text-black mt-0 mb-2" >
              <div class="form-floating mb-2 ">
                {{ form_endereco.codigo_postal  }}
                <label for="codigo_postal">Codigo Postal</label>
            </div>
               <div class="form-floating mb-2 ">
                  {{ form_endereco.rua }}
                  <label for="id_rua">Rua</label>
              </div>
              
              <div class="form-floating mb-2  ">
                  {{ form_endereco.numero }}
                  <label for="id_numero">Número</label>
              
              </div>
              
              <div class="form-floating mb-2  ">
                  {{ form_endereco.bairro }}
                  <label for="id_bairro">Bairro</label>
                
              </div>
              
              <div class="form-floating mb-2  ">
                  {{ form_endereco.cidade }}
                  <label for="id_cidade">Cidade</label>
              </div>
              
              <div class="form-floating mb-2  ">
                  {{ form_endereco.estado }}
                  <label for="id_estado">Estado</label>
                  
              </div>
              
              <div class="form-floating mb-2  ">
                  {{ form_endereco.descricao }}
                  <label for="id_descricao">Descrição</label>
              </div>
              
                <button type="submit" class="btn btn-primary mx-auto " >Salvar</button>
            </form>
            {% endif%}
        </div>
      </div>
    </div>
  </div>
  <style>
    
    .form-check input[type="checkbox"] {
        vertical-align: middle; /* Alinha verticalmente os inputs */
        margin-right: 5px; /* Ajusta a margem direita para separar o input do label */
    }

    .form-check-label {
        vertical-align: middle; /* Alinha verticalmente os labels */
    }
</style>
{% if form_loja %}   
    <script>
   
    function applyValidationClasses(form) {
        const inputs = form.querySelectorAll('.form-control-validate');
        inputs.forEach(input => {
            if (input.value.trim() === '') {
                // Ignora a validação para o campo descricao
                if (input.id !== 'id_descricao') {
                    input.classList.add('is-invalid');
                }
            }
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('form_cadastro');
        
        if( document.getElementById('horario_operacao_inicio')){
            // Alterar o tipo do campo "horario_operacao_inicio" para "time"
            document.getElementById('horario_operacao_inicio').type = 'time';
    
            // Alterar o tipo do campo "horario_operacao_fim" para "time"
            document.getElementById('horario_operacao_fim').type = 'time';
        }
        form.addEventListener('submit', function (event) {
            event.preventDefault();

            resetValidationClasses(form);

            if (validateForm(form)) {
                form.submit();
            } else {
                applyValidationClasses(form);
            }
        });

        const inputs = form.querySelectorAll('.form-control-validate');
        inputs.forEach(input => {
            input.addEventListener('input', function() {
                resetValidationClass(input);
            });
        });

        // ... (seu código existente para configurar o tipo do input 'time') ...

        function resetValidationClasses(form) {
            const inputs = form.querySelectorAll('.form-control-validate');
            inputs.forEach(input => {
                resetValidationClass(input);
            });
        }

        function resetValidationClass(input) {
            input.classList.remove('is-invalid');
        }

        function validateForm(form) {
            const nomeLoja = form.querySelector('#id_nome').value.trim();
            const numeroTelefone = form.querySelector('#id_numero_telefone').value.trim();
            // Ajuste na validação para ignorar o campo descricao
            if (nomeLoja === '' || numeroTelefone === ''   ) {
                return false;
            }else{
                return true;
            }

        }
    });
</script>
{% endif%}

{% endblock %}