backend/setup/urls.py
# myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

urlpatterns = [
    path("api/", include("api.urls_api")),  # URLs da sua API
    re_path(r"^.*$", TemplateView.as_view(template_name="index.html")),  # Rota do React
]

backend/api/models/ClienteModel.py
from .CustomModel import CustomModel
from django.db import models
from .EmpresaModel import EmpresaModel
from .EnderecoModel import EnderecoModel
from django.utils import timezone
import uuid
from api.utils import Utils


class ClienteModel(CustomModel):
    id_cliente = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    nome = models.CharField(max_length=255)
    telefone = models.CharField(max_length=20, null=True)
    ultima_compra = models.DateField(null=True, blank=True)
    tipo_cliente = models.CharField(max_length=50, null=True, blank=True)
    descricao = models.CharField(max_length=300, null=True, blank=True)
    endereco = models.ForeignKey(EnderecoModel, on_delete=models.SET_NULL, null=True)
    empresa = models.ForeignKey(EmpresaModel, on_delete=models.CASCADE, null=True)
    class Meta:
        db_table = 'cliente'

backend/api/models/ConfiguracaoModel.py
import uuid
from .CustomModel import CustomModel
from django.db import models
from .UsuarioModel import UsuarioModel
from django.utils import timezone
from api.utils import Utils

class ConfiguracaoModel(CustomModel):
    id_configuracao = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    usuario = models.ForeignKey(UsuarioModel, on_delete=models.CASCADE, null=True)
    codigo = models.IntegerField(null=True)
    titulo = models.TextField(blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)
    descricao_interna = models.TextField(blank=True, null=True)
    status_acesso = models.BooleanField(default=True)
    class Meta:
        db_table = 'configuracao'

backend/api/models/CustomModel.py
from django.db import models
from django.utils import timezone
import datetime

class CustomModel(models.Model):
    _insert = models.DateTimeField(auto_now_add=True, editable=False)
    _update = models.DateTimeField(auto_now=True)

    @property
    def update(self):
        """
        Retorna a data de atualização formatada no padrão brasileiro.
        """
        return self._update.strftime("%d/%m/%Y %H:%M")

    @update.setter
    def update(self, value):
        """
        Define a data de atualização com um valor datetime.
        """
        if isinstance(value, datetime.datetime):
            self._update = value
        else:
            raise ValueError("O valor deve ser uma instância de datetime")

    def save(self, *args, **kwargs):
        # Atualiza o campo '_update' com a data e hora atuais antes de salvar
        self._update = timezone.now()
        super().save(*args, **kwargs)

    class Meta:
        abstract = True

backend/api/models/UsuarioModel.py
from django.db import models
from django.utils import timezone
import uuid
from api.utils import Utils
from api.models import EmpresaModel
from .CustomModel import CustomModel  


class UsuarioModel(CustomModel):
    id_usuario = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    nome_completo = models.CharField(max_length=255)
    nome_usuario = models.CharField(max_length=50)
    senha = models.CharField(max_length=200)
    nivel_usuario = models.IntegerField()
    status_acesso = models.BooleanField(default=False)
    email = models.EmailField(max_length=255)
    ultimo_login = models.DateTimeField(null=True)
    empresa = models.ForeignKey(EmpresaModel, on_delete=models.CASCADE)
    class Meta:
        db_table="usuario"

class PersonalizacaoModel(CustomModel):
    id_personalizacao = models.UUIDField(
        default=uuid.uuid4, primary_key=True, editable=False
    )
    usuario = models.ForeignKey(UsuarioModel, on_delete=models.CASCADE)
    chave = models.CharField(max_length=255)
    valor = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)
    descricao_interna = models.CharField(max_length=255)
    codigo = models.CharField(max_length=255)
    class Meta:
        db_table="personalizacao"

backend/api/views/ClienteView.py
from api.utils import Utils
from api.user import UserInfo
from api.permissions import CustomPermission
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action        
from api.services import ClienteService, EnderecoService
import json
 
 
class ClienteView(viewsets.ViewSet):
    permission_classes = [CustomPermission]  # Permissão base

    def get_permissions(self):
        """
        Ajusta as permissões dinamicamente com base na view.
        """

        permissions = [permission() for permission in self.permission_classes]
        for permission in permissions:
            if isinstance(permission, CustomPermission):
                # Ajuste os parâmetros conforme necessário
                permission.codigo_model = "cliente"
                permission.auth_required = True
        return permissions

    
    def create(self, request):
        try:
            data = json.loads(request.body)
            empresa_id = UserInfo.get_id_empresa(request)

            cliente_data = data.get("cliente", {})
            cliente_data["empresa"] = empresa_id
            
            # Criar o cliente
            cliente, status_cliente, msg_cliente = ClienteService.create_cliente(cliente_data)
            
            if status_cliente:
                response_data = Utils.modelo_para_json(cliente)
                return Response({
                    "success": status_cliente,
                    "data": response_data,
                    "message": msg_cliente
                })
            else:
                return Response({
                    "success": False,
                    "message": msg_cliente
                }, status=status.HTTP_400_BAD_REQUEST)
        except json.JSONDecodeError:
            return Response({
                "error": "Erro ao processar dados JSON."
            }, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({
                "error": str(e)
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=True, methods=['put'], url_path='atualizar')
    def put(self, request, pk=None):
        """Handle PUT requests to update a cliente by ID."""
        try:
            cliente_data = request.data.get("cliente", {})

            if not cliente_data.get("id_cliente"):
                return Response({"success": False, "message": "ID do cliente não fornecido para atualização."}, status=status.HTTP_400_BAD_REQUEST)

            cliente, status_cliente, msg_cliente = ClienteService.update_cliente(cliente_data["id_cliente"], cliente_data)

            if status_cliente:
                return Response({ "data": Utils.modelo_para_json(cliente), "message": msg_cliente}, status=status.HTTP_200_OK)
            else:
                return Response({"success": False, "message": msg_cliente}, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=True, methods=['get'], url_path='detalhes')
    def get(self, request, pk=None):
        """Handle GET requests to retrieve a cliente by ID."""
        try:
            data = ClienteService.get_cliente(pk)
            if data.get('success'):
                return Response(data, status=status.HTTP_200_OK)
            return Response(data, status=data.get('status', status.HTTP_400_BAD_REQUEST))
        except Exception as e:
            return Response({"message": f"Ocorreu um erro ao processar a solicitação: {e}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=True, methods=['delete'], url_path='excluir')
    def delete_cliente(self, request, pk=None):
        """Handle DELETE requests to delete a cliente by ID."""
        empresa_id = UserInfo.get_id_empresa(request)
        
        # Chama o serviço para excluir o cliente e obtém a resposta
        success, message = ClienteService.delete_cliente(pk, empresa_id)
        
        # Define o status HTTP baseado no sucesso da operação
        if success:
            return Response({ "message": message}, status=status.HTTP_200_OK)
        else:
            return Response({"success": False, "message": message}, status=status.HTTP_400_BAD_REQUEST)

    @action(detail=False, methods=['get'], url_path='clientes-empresa')
    def get_clientes_by_empresa(self, request):
        try:
            empresa_id = UserInfo.get_id_empresa(request)
            clientes_data = ClienteService.get_clientes_by_empresa(empresa_id)
            
            # Verifica se há dados retornados e determina o status
            if clientes_data:
                return Response({ "data": clientes_data}, status=status.HTTP_200_OK)
            else:
                return Response({"message": "Não foram encontrados clientes para esta empresa."}, status=status.HTTP_404_NOT_FOUND)

        except Exception as e:
            return Response({"error": "Erro interno do servidor."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=False, methods=['get'], url_path='clientes')
    def get_cliente(self, request):
        empresa_id = UserInfo.get_id_empresa(request)
        response_data, status_code = ClienteService.get_cliente(empresa_id)
        return Response(response_data, status=status_code)

    @action(detail=True, methods=['get'], url_path='vendas')
    def get_vendas_by_cliente(self, request, pk=None):
        response_data, status_code = ClienteService.get_vendas_by_cliente(pk)
        return Response(response_data, status=status_code)

backend/api/views/ConfiguracaoView.py
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action
from api.services import ConfiguracaoService
from api.models import ConfiguracaoModel
from api.serializers import ConfiguracaoSerializer
from api.user import UserInfo
from api.permissions import CustomPermission

class ConfiguracaoView(viewsets.ViewSet):
    permission_classes = CustomPermission(codigo_model="configuracao", auth_required=True)

    @action(detail=False, methods=['get'], url_path='usuario/(?P<id_usuario>\d+)/')
    def get_configuracoes_usuario(self, request, id_usuario=None):
        response_data, status_code = ConfiguracaoService.get_configuracoes_usuario(id_usuario)
        return Response(response_data, status=status_code)

    @action(detail=False, methods=['post'], url_path='session/(?P<id_usuario>\d+)/')
    def configuracao_set_session(self, request, id_usuario=None):
        response_data, status_code = ConfiguracaoService.configuracao_set_session(request, id_usuario)
        return Response(response_data, status=status_code)

    @action(detail=False, methods=['post'], url_path='criar-padrao/')
    def criar_configuracoes_padrao(self, request):
        listModel = request.data.get('listModel', [])
        response_data, status_code = ConfiguracaoService.criar_configuracoes_padrao(listModel)
        return Response(response_data, status=status_code)

    @action(detail=False, methods=['get'], url_path='listar-padrao/')
    def list_configuracoes_padrao(self, request):
        usuario = UserInfo.get_id_usuario(request)
        response_data = ConfiguracaoService.list_configuracoes_padrao(usuario)
        return Response({"data": response_data, "success": True}, status=status.HTTP_200_OK)

backend/api/views/EmpresaView.py
# views.py
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.decorators import action
from api.models import EmpresaModel
from api.serializers import EmpresaSerializer
from api.services import  EmpresaService
from api.permissions import CustomPermission

class EmpresaView(viewsets.ViewSet):
    permission_classes = [CustomPermission(codigo_model="empresa", auth_required=True)]

    def list_private(self, request):
        try:
            empresas = EmpresaService.get_all_empresas()
            serializer = EmpresaSerializer(empresas, many=True)
            return Response({"data": serializer.data, "success": True}, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def create(self, request):
        serializer = EmpresaSerializer(data=request.data)
        if serializer.is_valid():
            try:
                empresa = EmpresaService.create_empresa(serializer.validated_data)
                return Response({"data": EmpresaSerializer(empresa).data, "success": True}, status=status.HTTP_201_CREATED)
            except Exception as e:
                return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)
        return Response({"error": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)

    def retrieve(self, request, pk=None):
        try:
            empresa = EmpresaService.get_empresa_by_id(pk)
            serializer = EmpresaSerializer(empresa)
            return Response({"data": serializer.data, "success": True}, status=status.HTTP_200_OK)
        except EmpresaModel.DoesNotExist:
            return Response({"error": "Empresa não encontrada"}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def update(self, request, pk=None):
        try:
            empresa = EmpresaService.get_empresa_by_id(pk)
            serializer = EmpresaSerializer(empresa, data=request.data, partial=True)
            if serializer.is_valid():
                updated_empresa = EmpresaService.update_empresa(pk, serializer.validated_data)
                return Response({"data": EmpresaSerializer(updated_empresa).data, "success": True}, status=status.HTTP_200_OK)
            return Response({"error": serializer.errors}, status=status.HTTP_400_BAD_REQUEST)
        except EmpresaModel.DoesNotExist:
            return Response({"error": "Empresa não encontrada"}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    def destroy(self, request, pk=None):
        try:
            EmpresaService.delete_empresa(pk)
            return Response({"success": True}, status=status.HTTP_204_NO_CONTENT)
        except EmpresaModel.DoesNotExist:
            return Response({"error": "Empresa não encontrada"}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=False, methods=['get'], url_path='telefone/(?P<telefone>[\d\+\-\s]+)')
    def telefone_existe(self, request, telefone=None):
        existe = EmpresaService.telefone_existe(telefone)
        return Response({"existe": existe}, status=status.HTTP_200_OK)

    @action(detail=False, methods=['get'], url_path='cpf/(?P<cpf>\d{11})')
    def cpf_existe(self, request, cpf=None):
        existe = EmpresaService.cpf_existe(cpf)
        return Response({"existe": existe}, status=status.HTTP_200_OK)

    @action(detail=False, methods=['get'], url_path='cnpj/(?P<cnpj>\d{14})')
    def cnpj_existe(self, request, cnpj=None):
        existe = EmpresaService.cnpj_existe(cnpj)
        return Response({"existe": existe}, status=status.HTTP_200_OK)

backend/api/views/EnderecoView.py
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from api.permissions import CustomPermission
from api.services import  EnderecoService
from api.models import EnderecoModel
from api.utils import Utils

class EnderecoView(viewsets.ViewSet):
    permission_classes = [CustomPermission(codigo_model="endereco", auth_required=True)]

    @action(detail=False, methods=['post'])
    def create_endereco(self, request):
        data = request.data
        endereco, status_success, msg = EnderecoService.create_endereco_data(data)
        if status_success:
            response_data = Utils.modelo_para_json(endereco)
            return Response({"success": status_success, "data": response_data, "message": msg}, status=status.HTTP_201_CREATED)
        return Response({"success": status_success, "message": msg}, status=status.HTTP_400_BAD_REQUEST)

    @action(detail=True, methods=['put'])
    def update_endereco(self, request, pk=None):
        endereco_id = pk
        data = request.data
        endereco, status_success, msg = EnderecoService.update_endereco_data(endereco_id, data)
        if status_success:
            return Response({"success": status_success, "data": Utils.modelo_para_json(endereco), "message": msg}, status=status.HTTP_200_OK)
        return Response({"success": status_success, "message": msg}, status=status.HTTP_404_NOT_FOUND)

backend/api/views/ErroView.py
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse


from api.permissions import CustomPermission
from rest_framework import viewsets, status

class ErroView(viewsets.ViewSet):
    permission_classes = [CustomPermission(codigo_model="configuracao", auth_required=True)]

    @staticmethod
    def erro(request, error_message):
        return JsonResponse({"error_message": error_message}, status=500)

backend/api/templates/usuario/modal_usuario.html
{% block content %}
    <div class="modal fade" id="ModalUsuario"   data-bs-backdrop="static"  data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog  modal-md modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title fw-bold font-monospace" id="lojaModalLabel" >
                    {% if text_usuario %} Detalhes do Usuário{% endif%}
                    {% if form_usuario %} Formulario do Usuário{% endif%}
                </h5>
                </div>
                    {% if text_usuario %} 
                   
                    <div class="modal-body font-monospace">
                        <h5 class="fw-bold">{{ text_usuario.nome_completo }}</h5>
                        <div class="card mt-3">
                            <div class="card-body">
                            <i class="bi bi-person"></i> ID do Usuário: <small class="fw-bold">{{ text_usuario.id_usuario }}</small></p>
                            <i class="bi bi-person-circle"></i> Nome do Usuário: <small class="fw-bold">{{ text_usuario.nome_usuario }}</small></p>
                            <i class="bi bi-envelope"></i>  Email: <small class="fw-bold">{{ text_usuario.email }}</small></p>
                            <!-- Adicione outros campos conforme necessário -->
                        </div>
                    </div>
                        <div class="card mt-3">
                            <div class="card-body">
                            <p class="fw-bold">  <i class="bi bi-calendar"></i> Inserção: <small class="fw-bold">{{ text_usuario.insert }}</small></p>
                            <p class="fw-bold">  <i class="bi bi-calendar"></i> Atualização: <small class="fw-bold">{{ text_usuario.update }}</small></p>
                              <p class="fw-bold"> 
                                <i class="bi bi-graph-up"></i> 
                                Nível do Usuário: 
                                <small class="fw-bold">
                                    {% if text_usuario.nivel_usuario == 1 %}
                                        Administrador
                                    {% elif text_usuario.nivel_usuario == 2 %}
                                        Gerente
                                    {% elif text_usuario.nivel_usuario == 3 %}
                                        Colaborador
                                    {% else %}
                                        Papel Desconhecido
                                    {% endif %}
                                </small>
                            </p>
                            <p class="fw-bold">
                                <i class=" bi-circle-fill  {% if text_usuario.status_acesso %}text-success{% else %}text-danger{% endif %}"></i> 
                                Status: <small class="fw-bold">{% if text_usuario.status_acesso %}Autorizado{% else %}Não Permitido{% endif %}</small>
                            </p>
                            
 
                            <p class="fw-bold"> <i class="bi bi-clock"></i> Último Login: <small class="fw-bold">{{ text_usuario.ultimo_login }} </small></p>
                        </div>
                    </div>
                    
                        {% for associado_info in associados_list %}
                        <div class="card mt-3">
                            <div class="card-body">
                                <p class="fw-bold"><i class="bi bi-shop"></i> {{ associado_info.nome }}</small></p>
                                <p class="fw-bold"> 
                                    <i class="{% if associado_info.status == 'Autorizado' %}text-success{% else %}text-danger{% endif %}  bi-circle-fill"></i> 
                                    Status: <small class="fw-bold">{{ associado_info.status }}</small>
                                </p>
                                 
                                    <p class="fw-bold"><i class="bi bi-clock"></i> Atualizado em: <small class="fw-bold">{{ associado_info.atualizado }}</small></p> 
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="modal-footer ">
                        <a href="{% url 'listar_usuarios' %}" class="btn btn-secondary mx-auto btn-sm">Fechar</a>
        
                    </div>  
                {% endif%}
                {% if form_usuario %}   
                <div class="modal-body  font-monospace"   >

                <form method="post" id="form_cadastro" class="needs-validation" autocomplete="off" novalidate>
                
                    {% csrf_token %}
                    <div class="form-floating mb-2">
                        {{ form_usuario.nome_completo }} 
                        <label for="nome_completo">Nome Responsável:</label>
                        <div class="invalid-feedback ms-2">
                            insira o nome.
                        </div>
                    </div>
                {% if  not isEditar %} 
                    <div class="form-floating mb-2">
                        {{ form_usuario.nivel_usuario }} 
                        <label for="id_nivel_usuario">Nível de Usuário:</label>
                    </div>
                {% endif%}

                {% if form_usuario.nivel_usuario.value > 1 %} 
                    <div class="form-floating mb-2">
                        {{ form_usuario.nivel_usuario }} 
                        <label for="id_nivel_usuario">Nível de Usuário:</label>
                    </div>
                    <div class="form-floating mb-2">
                        {{ form_usuario.status_acesso }}
                        <label for="id_status_acesso">Status:</label>
                    </div>
                {% endif%}

                    {% if not isEditar  %} 
                    <div class="form-floating mb-2">
                         {{form_usuario.email }}
                        <label for="email_responsavel">E-mail do Responsável</label>
                        <div class="invalid-feedback ms-2">Por favor, insira um Email válido.</div>
                    </div>
                
                    <div class="form-floating mb-2">
                         {{ form_usuario.senha }}  
                        <label for="senha">Senha</label>
                        <div class="invalid-feedback ms-2" id="senha-feedback"></div>
                    </div>
                    {% endif%}
                    <div class="list-group">

                    {% for loja in list_lojas %}
                    <label class="list-group-item d-flex gap-2">
                        <input type="checkbox" name="status_acesso_{{ loja.id_loja }}" class="form-check-input -auto"   {% if loja.status_acesso == True    %}checked{% endif %}>
                        <span>
                            <p style="font-size: 0.8rem;" class="font-monospace p-0 m-0 fw-bold" >{{ loja.nome }}</p>
                            <small style="font-size: 0.6rem;" class="d-block text-body-secondary">permitir o usuario ter acesso a essa loja, isso inclui, realizar vendas,acresentar produtos, entre outros</small>
                        </small></p>
                    </label>
                {% endfor %}
            </div>  
                        
 
                    
    {% if not isEditar  %} 

<script>   
    function validarEmail() {
                var email_responsavel = document.getElementById('id_email');
                var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                if (!emailRegex.test(email_responsavel.value)) {
                    email_responsavel.classList.add('is-invalid');
                } else {
                    email_responsavel.classList.remove('is-invalid');
                }
                }

                // Função para validar a senha
                function validarSenha(senha="") {
                    var senhaInput = document.getElementById("id_senha");
                    var senhaFeedback = document.getElementById("senha-feedback");
                    senha = senhaInput.value

                    if (senha.length < 8) {
                    senhaFeedback.innerHTML = "A senha deve ter no mínimo 8 caracteres.";
                    senhaInput.classList.add("is-invalid");
                    } else if (!/[A-Z]/.test(senha)) {
                    senhaFeedback.innerHTML = "A senha deve conter pelo menos uma letra maiúscula.";
                    senhaInput.classList.add("is-invalid");
                    } else if (!/[a-z]/.test(senha)) {
                    senhaFeedback.innerHTML = "A senha deve conter pelo menos uma letra minúscula.";
                    senhaInput.classList.add("is-invalid");
                    } else if (!/[0-9]/.test(senha)) {
                    senhaFeedback.innerHTML = "A senha deve conter pelo menos um número.";
                    senhaInput.classList.add("is-invalid");
                    } else {
                    senhaFeedback.innerHTML = "";
                    senhaInput.classList.remove("is-invalid");
                    }
                }
            </script>
    {% endif%}
        
<script>
    document.addEventListener('DOMContentLoaded', function() {

        document.getElementById('form_cadastro').addEventListener('submit', function(event) {
        // Impede o envio padrão do formulário
        event.preventDefault();
        
        // Função para validar os campos
        function ValidateInputs() {
            var nome_completo = document.getElementById('id_nome_completo');

    {% if form_usuario.nivel_usuario.value > 1 %} 
            var nivel_usuario = document.getElementById('id_nivel_usuario');
        {% endif%}    
    {% if not isEditar  %} 

            var email_responsavel = document.getElementById('id_email');
            var senha = document.getElementById('id_senha');
            email_responsavel.classList.remove('is-invalid');
            senha.classList.remove('is-invalid');
            var senhaFeedback = document.getElementById("senha-feedback");
            
            if (email_responsavel.value.trim() === '') {
                email_responsavel.classList.add('is-invalid');
            } else {
                var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
                if (!emailRegex.test(email_responsavel.value)) {
                    email_responsavel.classList.add('is-invalid');
                }
            }
        
            if (senha.value.trim() === '') {
                senha.classList.add('is-invalid');
                senhaFeedback.innerHTML = "preencha corretamente o campo.";
                
            } else {
                validarSenha(senha.value);
            }
    {% endif%}
        
            // Remove as classes 'is-invalid' de todos os campos antes de fazer a validação
            nome_completo.classList.remove('is-invalid');
            {% if form_usuario.nivel_usuario.value > 1 %} 
                nivel_usuario.classList.remove('is-invalid');
            {% endif%}
                
            // Verifica se os campos estão preenchidos corretamente
             
            if (nome_completo.value.trim() === "") {
                nome_completo.classList.add('is-invalid');
            }
            var camposInvalidos = document.querySelectorAll('.is-invalid');
            if (camposInvalidos.length > 0) {
                alertCustomer('Por favor, preencha corretamente os campos.');
                return false;
            }
                return true;
            }
        
        // Executa a validação dos campos
        if (ValidateInputs()) {
            this.submit();
        } else {
            return false;
        }
        });
    });
</script>    
                </div>

            <div class="modal-footer ">
                <a href="{% url 'listar_usuarios' %}" class="btn btn-secondary float-start me-auto btn-sm">Cancelar</a>
             <button type="submit" class="btn btn-primary float-end btn-md" >Salvar</button>

            </div>  

        </form>
        </div>

                    {% endif%}

            </div>
        </div>
    </div>


{% endblock %}